services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tpk-web
    ports:
      - "3003:3000"
    restart: always
    environment:
      - NODE_ENV=production
